# Generated by Django 5.2.10 on 2026-01-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_chef",
            field=models.BooleanField(
                default=False, help_text="Designates if this user has Chef privileges."
            ),
        ),
    ]
