# Generated by Django 5.2.10 on 2026-01-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_meal_mealrecipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Current amount in stock",
                max_digits=10,
            ),
        ),
    ]
