# Generated by Django 5.2.10 on 2026-01-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_meal_customer_price_meal_customer_price_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="unit_custom",
            field=models.CharField(
                blank=True,
                help_text="Custom unit label when using Other (custom).",
                max_length=50,
            ),
        ),
    ]
