# Generated by Django 5.2.10 on 2026-01-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_ingredient_unit_custom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="unit_type",
            field=models.CharField(
                choices=[
                    ("LB", "Pounds"),
                    ("OZ", "Ounces"),
                    ("G", "Grams"),
                    ("KG", "Kilograms"),
                    ("MG", "Milligrams"),
                    ("ML", "Milliliters"),
                    ("L", "Liters"),
                    ("TSP", "Teaspoons"),
                    ("TBSP", "Tablespoons"),
                    ("CUP", "Cups"),
                    ("PT", "Pints"),
                    ("QT", "Quarts"),
                    ("GAL", "Gallons"),
                    ("QTY", "Quantity/Count"),
                    ("OTHER", "Other (custom)"),
                ],
                max_length=5,
            ),
        ),
    ]
